### ISSUE TITLE
容器运行不起来

### ISSUE THREAD

**Issue by gaoyaxuan** [doringland/ud4d#1]
Traceback (most recent call last):
  File "keep_alive.py", line 1, in <module>
    from ud4d.api import start_as_server
  File "/usr/local/lib/python3.7/site-packages/ud4d/api.py", line 5, in <module>
    from ud4d.docker_manager import DeviceContainerManager
  File "/usr/local/lib/python3.7/site-packages/ud4d/docker_manager.py", line 18, in <module>
    raise e
  File "/usr/local/lib/python3.7/site-packages/ud4d/docker_manager.py", line 15, in <module>
    device_image = client.images.get(device_image_name)
  File "/usr/local/lib/python3.7/site-packages/docker/models/images.py", line 316, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/image.py", line 245, in inspect_image
    self._get(self._url("/images/{0}/json", image)), True
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 262, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 258, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("no such image: williamfzc/adb_tester:0.1: No such image: williamfzc/adb_tester:0.1")
root@ming-System-Product-Name:/usr/bin# docker pull williamfzc/adb_tester:0.1
Error response from daemon: manifest for williamfzc/adb_tester:0.1 not found

需要williamfzc/adb_tester:0.1 这个,可是你release的tag是williamfzc/adb_tester:0.1.0

下载下来,改完tag,再启动容器,有插手机,但是一直返回null.
ubuntu 16 系统

**Comment by williamfzc** [comment]
上面的问题是因为，一开始的设计是打算每个设备对应一个容器，然后通过容器关联来直接管理设备。后来因为时间关系没有落地，改用了服务器形式，让用户自行绑定设备。在后面的版本中只要在配置中打开`SIMPLE_MODE`（默认是打开的）将不会创建容器（[具体commit](https://github.com/doringland/ud4d/commit/6b30533016b74ef87f8dcf4c256f97a948e4d68c)），也就不会发生`adb_tester`之类的问题。

这边还是比较建议直接用docker运行ud4d的，环境相对也干净些，更加适用于正式环境且更方便。参考[这里](https://github.com/doringland/ud4d#docker)

关于设备连接的问题，在启动ud4d容器之后，是需要重新插拔设备一次才能检测到的（因为没有插拔不会产生插拔事件，也就无法获取到具体绑定的位置）。

**Comment by williamfzc** [comment]
你好，这个问题确实存在，是之前我本地有两个已经构建完成的镜像所以没有发现。
现在已经修复了，只需要拉取最新的镜像跑就没有问题。
谢谢反馈：）
